# Generated by Django 3.2.9 on 2021-11-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csia_app', '0005_subjectstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('file', models.FileField(upload_to='static/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csia_app.taskstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csia_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csia_app.subject')),
            ],
        ),
    ]
