# Generated by Django 3.2.9 on 2021-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csia_app', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
